### ISSUE TITLE
sqlalchemy.exc.OperationalError: (psycopg.OperationalError) connection failed: FATAL:  role "ai" does not exist

### ISSUE THREAD

**Issue by justinqcai** [phidatahq/phidata#127]
Hi, I'm new here so this may be silly but following the ['assistant knowledge cookbook'](https://github.com/phidatahq/phidata/tree/main/cookbook/knowledge) instructions leads only to the following error in the console, complaining about lack of an 'ai' role.
`sqlalchemy.exc.OperationalError: (psycopg.OperationalError) connection failed: FATAL:  role "ai" does not exist
(Background on this error at: https://sqlalche.me/e/20/e3q8)`

Any idea why this might be happening? I'm looking to contribute so I'd definitely like to get my local working.

**Comment by ashpreetbedi** [comment]
@justinqcai this happens when you already have a PgVector volume meaning the init db couldn't create the `ai` role. No worries the easiest path for us is to use a different name for the PgVector database. Update your `cookbook/knowledge/resources.py` file to:

```
from phi.docker.app.postgres import PgVectorDb
from phi.docker.resources import DockerResources

# -*- PgVector running on port 5532:5432
vector_db = PgVectorDb(
    name="knowledge-db",
    pg_user="ai",
    pg_password="ai",
    pg_database="ai",
    host_port=5532,
)

# -*- DockerResources
dev_docker_resources = DockerResources(apps=[vector_db])
```

Then run `phi start cookbook/knowledge/resources.py -y` and it should work

I've update the [resources file in the cookbook](https://github.com/phidatahq/phidata/blob/main/cookbook/knowledge/resources.py) as well so you can just pull from main to get the new code.

Let me know if you still face an issue :)

**Comment by justinqcai** [comment]
Awesome, thanks! It looks like [the resources file in /cookbook/rag](https://github.com/phidatahq/phidata/blob/main/cookbook/rag/resources.py) and the whole folder in general looks to be a duplicate, just wanted to bring that up as well before closing this thread out

**Comment by ashpreetbedi** [comment]
@justinqcai that is correct, the duplicates are intentional as users usually look for RAG/PDF cookbooks which are the duplicates but make it easier for users to search. im open to suggestions here :)

**Comment by justinqcai** [comment]
@ashpreetbedi That makes sense, in that case my only suggestion would be to update [that file](https://github.com/phidatahq/phidata/blob/main/cookbook/rag/resources.py) with the same changes you made [here](https://github.com/phidatahq/phidata/blob/main/cookbook/knowledge/resources.py) so users can run the RAG cookbook properly! Thanks Ash

**Comment by ashpreetbedi** [comment]
Very good idea @justinqcai, will do that
