### ISSUE TITLE
ddg ollama agent issue?

### ISSUE THREAD

**Issue by hemanth** [phidatahq/phidata#1524]
I like phidata's interface and trying to bake an agent with ollama with the below code: 

```python
from phi.agent import Agent
from phi.model.ollama import Ollama
from phi.tools.duckduckgo import DuckDuckGo

web_agent = Agent(
    name="Web Agent",
    model=Ollama(id="llama3.2"),
    tools=[DuckDuckGo()],
    instructions=["Always include sources"],
    show_tool_calls=True,
    markdown=True,
)
web_agent.print_response("Whats happening in France?", stream=True)
```

But not seeing a response:

<img width="971" alt="image" src="https://github.com/user-attachments/assets/aba1e182-cd24-4052-8938-0631fd780c66">

Versions: 

```
phidata           2.6.1
duckduckgo_search 6.3.7
```

Am I missing something here?

**Comment by ysolanky** [comment]
Hey @Hemanth, We have noticed that Llama 3.2 isn’t the best option for function calling. The Llama 3.1:8b model provides a significantly better performance. Could you try running your Agent again with `model=Ollama(id="llama3.1:8b")` and see how it works? Thanks!

**Comment by mprisznyak** [comment]
Hi @ysolanky, 

This code works both with llama3.1 and 3.2  if I remove "stream=True".

Otherwise I'm getting garbage answers like these for both models:

 Based on the provided functions, I'll call the duckduckgo_search function with a query for "France" and a maximum number of results set to 10.                                        ┃
┃                                                                                                                                                                                       ┃
┃ Response:                                                                                                                                                                             ┃
┃                                                                                                                                                                                       ┃
┃                                                                                                                                                                                       ┃
┃  {                                                                                                                                                                                    ┃
┃      "name": "duckduckgo_search",                                                                                                                                                     ┃
┃      "parameters": {                                                                                                                                                                  ┃
┃          "max_results": 10,                                                                                                                                                           ┃
┃          "query": "France"                                                                                                                                                            ┃
┃      }                                                                                                                                                                                ┃
┃  }                                                                                                                                                                                    ┃
┃                                                                                                                                                                                       ┃
┃                                                                                                                                                                                       ┃
┃ This will return the latest search results from DuckDuckGo for the query "France". 

or 

 Tool call response: {"name": "duckduckgo_search", "parameters": {"max_results": 10, "query": "France news"}}                                                                          ┃
┃                                                                                                                                                                                       ┃
┃ Based on the tool call response:                                                                                                                                                      ┃
┃                                                                                                                                                                                       ┃
┃  • The function to use is duckduckgo_search.                                                                                                                                          ┃
┃  • The arguments are:                                                                                                                                                                 ┃
┃     • max_results: 10                                                                                                                                                                 ┃
┃     • query: "France news"                                                                                                                                                            ┃
┃                                                                                                                                                                                       ┃
┃ The resulting JSON for a function call with its proper arguments that best answers the given prompt is:                                                                               ┃
┃                                                                                                                                                                                       ┃
┃ {"name": "duckduckgo_search", "parameters": {"max_results": 10, "query": "France news"}}    


                                                                                                                                                                                   ┃
┃ I don't have the ability to call tools or access external information. However, based on the provided function descriptions, I can suggest a potential tool call that might       ┃
┃ answer your question.                                                                                                                                                             ┃
┃                                                                                                                                                                                   ┃
┃ {"name": "duckduckgo_search", "parameters": {"query": "France news", "max_results": 10}}                                                                                          ┃
┃                                                                                             

or 

┃ Tool Call Response                                                                                                                                                                ┃
┃                                                                                                                                                                                   ┃
┃ {"name": "duckduckgo_search", "parameters": {"max_results": "10", "query": "whats happening in France"}}

**Comment by hemanth** [comment]
Ah, now I am hitting TLS issue, maybe my server certs are screwed? 

```
 error trying to 
         connect: TLS handshake failed: cert verification failed - self signed  
         certificate in certificate chain [CERTIFICATE_VERIFY_FAILED]           
                                                                                
         Caused by:                                                             
             0: error trying to connect: TLS handshake failed: cert verification
         failed - self signed certificate in certificate chain                  
         [CERTIFICATE_VERIFY_FAILED]                                            
             1: TLS handshake failed: cert verification failed - self signed    
         certificate in certificate chain [CERTIFICATE_VERIFY_FAILED]           
             2: [CERTIFICATE_VERIFY_FAILED]                                     
             3: [CERTIFICATE_VERIFY_FAILED]  
         ```

**Comment by mprisznyak** [comment]
@hemanth 

It works for me.  

I had a quick look at the Duckduckgo tool and I saw that it  uses Primp as its HTTP client.  
 https://github.com/deedy5/primp 
 
So Primp cannot establish an HTTPS connection. It seems the certification chain Primp uses is wrong on your machine.

**Comment by ysolanky** [comment]
Hello @mprisznyak! Ollama recently updated the spec for tool call streaming. Can you please make sure your Ollama package is updated by running: pip install -U Ollama

**Comment by mprisznyak** [comment]
@ysolanky 

Hi, I'm using poetry because that's so much better than pip.. :)
I'm already on the latest version of ollama, on 0.4.4. 
https://pypi.org/project/ollama/

**Comment by hemanth** [comment]
> This is an issue that is entirely unrelated to Phidata
The first part yes; The cert part no.

**Comment by ysolanky** [comment]
Hey @mprisznyak ! I am not able to replicate your errors with Ollama tool call streaming. I just tested this example: https://github.com/phidatahq/phidata/blob/main/cookbook/providers/ollama/web_search.py and everything is working as expected. Here are my library versions:

```
ollama == 0.4.3
phidata == 2.6.4
duckduckgo_search == 6.3.7
```

**Comment by hemanth** [comment]
For anyone else facing the issues: 

```
export CA_CERT_FILE="/home/user/cert.pem"
```

<img width="1703" alt="image" src="https://github.com/user-attachments/assets/415348cd-eadf-423c-a8c1-29343432e8f5">

**Comment by ysolanky** [comment]
@mprisznyak in phidata v2.6.1 we updated the tool call streaming logic to match the latest Ollama specification. The response that you are getting is expected on phidata versions <2.6.1 with the latest Ollama version. Is is possible for you to create a new venv and test again? I again tested with both llama 3.2 and llama 3.1 and I am getting the expected output (The tool calls are being executed)

**Comment by mprisznyak** [comment]
@ysolanky 

As my screenshot showed, I'm on phidata 2.6.4  and I have downgraded to ollama 0.4.3  and then I saw this behaviour. 
Just upgraded to ollama 0.4.4 (latest) and there was no change.

What configuration do you want me to test with, please?

**Comment by ysolanky** [comment]
@mprisznyak this is quite odd. An explanation that I can think of is an issue with your virtual environment. Can you please create a new virtual env using:

`python3 -m venv venv`
And then activate it using:
`source "venv/bin/activate"`
And then do a fresh installation of phidata and Ollama. Sorry about this. Hoping to resolve this issue for you. Please feel free to join our discord here: https://discord.gg/U5PXYzH6

**Comment by mprisznyak** [comment]
@ysolanky 

I have just created a fresh environment to test this:

`$ cat pyproject.toml 
[tool.poetry]
name = "phidata-test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
phidata = "^2.6.4"
ollama = "^0.4.4"
duckduckgo-search = "^6.3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

It's highly unlikely that pip or poetry matters..

![image](https://github.com/user-attachments/assets/b4f0f011-f852-4486-81bd-8ff413b13725)

It does work if I remove "stream=True"

Using

from phi.model.ollama import Ollama
model=Ollama(id="llama3.2:latest")






`

**Comment by ysolanky** [comment]
@mprisznyak thanks for sharing! I too did a fresh install but I am not able to replicate your error with streaming + tool call. We made a breaking change in v2.6.1 but it should work for you on v2.6.3. Can you please set the debug_mode = True in your agent config and share debug logs to help give me an idea about what could be going on. Set the debug mode in the following way:

```python
agent = Agent(
    model=Ollama(id="llama3.1:8b"),
    tools=[YFinanceTools(stock_price=True, analyst_recommendations=True)],
    instructions="Use tables to display data.",
    show_tool_calls=True,
    markdown=True,
    debug_mode=True,
)
```

**Comment by mprisznyak** [comment]
Ok, here is the debug when it doesn't work:

`
(chatbotpoc-py3.12) (base) prisz@prisztop:~/PycharmProjects/chatbotPOC$ python web_search.py 
DEBUG    Debug logs enabled                                                                                                                                                              
DEBUG    *********** Agent Run Start: e95c3aed-817c-4fc4-9d80-3dd503b20f84 ***********                                                                                                   
DEBUG    Function duckduckgo_search from duckduckgo added to model.                                                                                                                      
DEBUG    Function duckduckgo_news from duckduckgo added to model.                                                                                                                        
DEBUG    ---------- Ollama Response Start ----------                                                                                                                                     
DEBUG    ============== system ==============                                                                                                                                            
DEBUG    ## Instructions                                                                                                                                                                 
         - Always include sources                                                                                                                                                        
         - Use markdown to format your answers.                                                                                                                                          
DEBUG    ============== user ==============                                                                                                                                              
DEBUG    Whats happening in France?                                                                                                                                                      
DEBUG    ============== assistant ==============                                                                                                                                         
DEBUG    To provide the best answer, we will use a function call to `duckduckgo_news` with the query "France".                                                                           
                                                                                                                                                                                         
         {"name": "duckduckgo_news", "parameters": {"max_results": "10", "query": "France"}}                                                                                             
DEBUG    **************** METRICS START ****************                                                                                                                                 
DEBUG    * Time to first token:         0.1996s                                                                                                                                          
DEBUG    * Time to generate response:   1.7532s                                                                                                                                          
DEBUG    * Tokens per second:           29.0902 tokens/s                                                                                                                                 
DEBUG    * Input tokens:                351                                                                                                                                              
DEBUG    * Output tokens:               51                                                                                                                                               
DEBUG    * Total tokens:                402                                                                                                                                              
DEBUG    **************** METRICS END ******************                                                                                                                                 
DEBUG    ---------- Ollama Response End ----------                                                                                                                                       
DEBUG    Added 2 Messages to AgentMemory                                                                                                                                                 
DEBUG    Added AgentRun to AgentMemory                                                                                                                                                   
DEBUG    --**-- Logging Agent Run                                                                                                                                                        
DEBUG    *********** Agent Run End: e95c3aed-817c-4fc4-9d80-3dd503b20f84 ***********                                                                                                     
┏━ Message ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                                                                                                       ┃
┃ Whats happening in France?                                                                                                                                                            ┃
┃                                                                                                                                                                                       ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Response (1.7s) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                                                                                                       ┃
┃ To provide the best answer, we will use a function call to duckduckgo_news with the query "France".                                                                                   ┃
┃                                                                                                                                                                                       ┃
┃ {"name": "duckduckgo_news", "parameters": {"max_results": "10", "query": "France"}}                                                                                                   ┃
┃                                                                                                                                                                                       ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
`

`
(chatbotpoc-py3.12) $ poetry  show | grep phidata
phidata            2.6.4       Build multi-modal Agents with memory, knowle...
(chatbotpoc-py3.12) (base) $ poetry  show | grep duck
duckduckgo-search  6.3.7       Search for words, documents, images, news, m...
(chatbotpoc-py3.12) $ poetry  show | grep ollama
ollama             0.4.4       The official Python client for Ollama.

`

**Comment by ysolanky** [comment]
@mprisznyak I think you need to update your Ollama version. Not the python package but the Ollama app

**Comment by mprisznyak** [comment]
@ysolanky 

I have updated to the latest ollama version 0.5.1 and now it all works fine with "stream=True", too.   
So the issue wasn't with phidata.  For posterity,  people should use a more recent Ollama server than 0.3.8 !

I'm sorry to waste your time. Thanks for your helpfulness and persistence!

**Comment by ysolanky** [comment]
No worries at all. Happy to have solved your issue!
