### ISSUE TITLE
error: phi ws up

### ISSUE THREAD

**Issue by ImYuya** [phidatahq/phidata#85]
I attempted to create a docker container by running `phi ws up` as below, but encountered an error. Docker itself is up and running without any issues.

```
> phi ws up                                                                  
Starting workspace: ai-app

--**-- Confirm resources to create:
  -+-> Network: ai
  -+-> Container: ai-db
  -+-> Container: ai-app

Network: ai
Total 3 resources

Confirm deploy [Y/n]: Y

-==+==- Network: ai
ERROR    Could not connect to docker. Please confirm docker is installed and running                    
ERROR    Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))    
```

**Comment by ysolanky** [comment]
What OS are you running the code on and what's the docker version?

**Comment by ysolanky** [comment]
Please confirm that docker is running. Also, try restarting docker. You can get that error when compose is not able to connect to docker via docker socket. From: [Link](https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version)

**Comment by ImYuya** [comment]
my OS is Mac
I restarted the docker, but the situation is the same.
The docker is running.
I can execute `docker compose up`  in another project.

Thank you

**Comment by ashpreetbedi** [comment]
Sorry this is happening because docker-py cannot access the `/var/run/docker.sock` file. Please can you confirm:

-  what is the output of `ls -l /var/run/docker.sock`
- If the file doesnt exist, please run `sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock`
- If this command fails, please share the output of `ls -l $HOME/.docker/run/docker.sock`

This should fix your issue, if it doesn't, please try: 

1. Run: `sudo docker ps`
2. Run `sudo chown $USER /var/run/docker.sock`
3. Run `sudo usermod -a -G docker $USER`

These should fix the permissions issue

**Comment by ashpreetbedi** [comment]
Here's more information from stackoverflow: https://stackoverflow.com/a/56592277

**Comment by ashpreetbedi** [comment]
also gonna add this to the documentation

**Comment by ashpreetbedi** [comment]
@ImYuya more info here: https://docs.phidata.com/faq/could-not-connect-to-docker

**Comment by ImYuya** [comment]
Thank you for your response and showing the solution in detail.
The results of the confirmation are listed below.

- what is the output of `ls -l /var/run/docker.sock`
   - ls: /var/run/docker.sock: No such file or directory
- If the file doesnt exist, please run `sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock`
   - This command was successful. 

The `phi ws up` command works!

**Comment by ashpreetbedi** [comment]
Thanks for bearing with us @ImYuya ! Here to help
